# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURACIÓN DEL SISTEMA DE DETECCIÓN DE CASCOS
# ═══════════════════════════════════════════════════════════════════════════════

# ── Modelos ──────────────────────────────────────────────────────────────
# models: Rutas a los modelos de procesamiento
#   - detection: Modelo YOLO que busca motos y cabezas en toda la pantalla.
#                Si dice ".engine" corre más rápido usando TensorRT.
#                Si dice ".pt" corre en PyTorch estándar.
#   - classification: Modelo YOLO-cls especializado en recortar la cabeza y decir si
#                     tiene o no tiene casco.
models:
  detection: "detector.engine"
  classification: "clasificador.pt"

# ── Video (Control de Tráfico) ────────────────────────────────────────────────
# Configura cómo se obtiene el video de la cámara antes de analizarlo.
#   - fps: La velocidad a la que FFmpeg extrae las fotos del stream en vivo.
#   - resolution: Achica el video nativo (ej: 1080p) a este tamaño en RAM.
#   - buffer_size: Cantidad de fotos que se guardan en la "sala de espera".
#                  Si se usa un número muy grande (ej: 20) se ve el video con retraso.
video:
  fps: 10
  resolution: [1280, 720]
  buffer_size: 1

# ── Detección ──────────────────────────────────────────
# Reglas matemáticas
#   - confidence_threshold: Umbral necesario para aceptar una MOTO.
#                           Como usamos un Tracker, conviene ponerlo bajo para que no pierda motos
#   - head_confidence: Umbral necesario para aceptar una CABEZA.
#                      Lo uso un poco más alto que el de moto, porque después se usa para clasificar y no quiero clasificar basura.
#   - inside_threshold: Porcentaje de la cabeza que DEBE estar DENTRO del recuadro de la moto.
#                       Trato de maximizarlo para no tomar cabezas de peatones o de otras motos
#   - process_interval: Tiempo de salto. En 0.0 procesa TODO lo que le manda FFmpeg.
#                       Conviene modificar directamente los FPS que se consumen y dejar esto en 0.
#   - frames_to_classify: Votos IDÉNTICOS (ej: 6 veces 'sin_casco') necesarios para 
#                         dictar una sentencia rápida. Si la IA junta estos votos, 
#                         clasifica a la moto al instante sin esperar más.
#   - max_frames_to_collect: Memoria máxima de evidencias. Guarda en RAM los X mejores cuadros 
#                            de la moto. Además, funciona como límite de tiempo: 
#                            si el total de frames que se vió la moto es el DOBLE de este valor, 
#                            el sistema fuerza un veredicto definitivo 
#                            contando la clase que más votos tiene.
#   - min_head_size: Tamaño mínimo en píxeles de una cabeza para intentar clasificarla.
#   - imgsz: El tamaño al que YOLO achica la foto internamente.
#   - effective_fps: Etiqueta informativa para los logs en consola.
detection:
  confidence_threshold: 0.30
  head_confidence: 0.50
  inside_threshold: 0.85
  process_interval: 0.0
  frames_to_classify: 7
  max_frames_to_collect: 14
  min_head_size: 15
  imgsz: 960
  effective_fps: 10

# ── Clasificación ────────────────────────────────────────────
#   - confidence_threshold: Umbral exigido para tomar una clasificación como verdadera.
#                           Implicancia: Si dice "sin_casco" pero con una confianza de 0.55
#                           se marca el frame como "indeterminado" y no suma votos,
#                           evitando que una clasificación "no confiable" genere un falso positivo.
#   - imgsz: Tamaño del recorte de la cabeza.
#            (Uso con el que fue entrenado el modelo, NO CAMBIAR)
classification:
  confidence_threshold: 0.70
  imgsz: 64

# ── Alertas ─────────────────────────────────────────────────────────────
#   - enabled: Prende/Apaga los modales y sonidos en la web.
#   - sound: Activa el pitido "beep" cuando salta un "sin_casco".
alerts:
  enabled: true
  sound: true

# ── Servidor web (Flask) ─────────────────────────────────────────────────────
server:
  host: "0.0.0.0"
  port: 5000
  debug: true

# ── Logging ────────────────────────────────────────────────────────────────────
#   - access_logs: muestra los logs de flask, apagado para mejos lectura
logging:
  access_logs: false

# ── Rutas de Almacenamiento ───────────────────────────────────────────────────
# Donde se guarda la evidencia de los infractores.
paths:
  database: "data/detections.db"
  crops_dir: "crops"

# ── Opciones de Guardado de Crops ──────────────────────────────────────────────
# Implicancia: Controla cuánto disco duro querés gastar.
#   - motos: Guarda la foto entera de la moto de los infractores (Recomendado = true).
#   - cabezas: Guarda solo los casquitos chiquitos.
#   - tracking: Guarda TODOS los frames de TODAS las motos.
save_crops:
  motos: true  
  cabezas: false
  tracking: false

# ═══════════════════════════════════════════════════════════════════════════════
# CÁMARAS
# ═══════════════════════════════════════════════════════════════════════════════
# Lista infinita de cámaras.
#   - source: Puede ser un .m3u8, un .mp4 local o un link directo.
cameras:
  # - id: 1
  #   name: "Tupã - Tamoios x Aimorés"
  #   source: "https://ipservice.aovivonanet.com.br:4433/hls/tupa-tamoios-x-aimores/index.m3u8"
  #   #source: "https://www.youtube.com/watch?v=HdaWcBamcSA"
  #   lat: -21.928436
  #   lng: -50.512060

  # - id: 2
  #   name: "Tupã - Tamoios x Caingangs"
  #   source: "https://ipservice.aovivonanet.com.br:4433/hls/tupa-tamois-x-caingangs/index.m3u8"
  #   #source: "https://www.youtube.com/watch?v=WSm_r0eNl1E"
  #   lat: -21.931936
  #   lng: -50.516157

  - id: 3
    name: "Tupã - Brasil x Caingangs"
    #source: "https://ipservice.aovivonanet.com.br:4433/hls/tupa-brasil-x-caingangs/index.m3u8"
    source: "https://www.youtube.com/watch?v=UemFRPrl1hk"
    lat: -21.925451
    lng: -50.522564